### ISSUE TITLE
官方文档更新了。

### ISSUE THREAD

**Issue by xfdywy** [imu-hupeng/cos-python3-sdk#6]
官方文档更新了。文件路径什么的已经不对了。
直接登录会提示 类似这样的：

You do not have permission to get URL '/files/v2/1253424161/test//test.png' from this server.

现在的文档类似这样：
https://cloud.tencent.com/document/product/436/14690

**Comment by chmod740** [comment]
建议问题描述上更加清晰一点，例如在调用那个方法上出现了报错，最好贴出报错信息。

**Comment by xfdywy** [comment]
基本上调用upload_file这样方法的都会报错。
例如你code的73行             
   self.url = 'http://<Region>.file.myqcloud.com/files/v2/<appid>/<bucket_name>/'。
现在已经不用这样的api去访问了。

最新版是v5 的sdk，api大概是这样的：
 url = u"{scheme}://{bucket}.{region}.myqcloud.com/{path}".format(
参见：
https://github.com/tencentyun/cos-python-sdk-v5/blob/master/qcloud_cos/cos_client.py#L87

还没有注意到登录机制有没有变化。大佬考虑更新一下吗？

**Comment by chmod740** [comment]
确认完毕，初始化COS时，你需要指定 region 参数,例如北京地域的cos，你需要这么指定：
cos = Cos('1234556', '', '', region="bj")

**Comment by chmod740** [comment]
未来可能根据新的API重写实现部分，所有接口保持不变
