### ISSUE TITLE
没办法上传文件，返回的url是none

### ISSUE THREAD

**Issue by dempsey123** [imu-hupeng/cos-python3-sdk#7]
def CreateFolder_Tecent():
    cos = Cos(app_id=1,secret_id='AKIDAlGaXKV5',secret_key='iEYfhYlhWBg097tX2Pdg',region='gz')
    bucket = cos.get_bucket("ExcelFile")
    bucket.create_folder("/ExcelFileUser")
    print("create bucket success")

def exportExcelFile():
    cos = Cos(app_id=1256960769,secret_id='AKIDAlGaXKVLZcT9exqi8PVP7ez97tTxOOK5',secret_key='iEYfhYFoESUKzSkYEilhWBg097tX2Pdg',region='gz')
    bucket = cos.get_bucket("ExcelFile")
    real_file_path="/Users/dempsey/Desktop/Sample.xlsx"
    file_name_inBucket = "Sample.xlsx"
    dir_name = "/ExcelFileUser"
    data=bucket.upload_file(real_file_path,file_name_inBucket,dir_name)
    query=bucket.query_folder(dir_name)
    print(data)
    print(query)
    return

**Comment by dempsey123** [comment]
已经尝试过24小时制的时间或者上下午的时间。都是返回none

**Comment by dempsey123** [comment]
![image](https://user-images.githubusercontent.com/26816616/42135729-dbf856a0-7d81-11e8-97b3-7d7105168580.png)

**Comment by dempsey123** [comment]
getbucket那部分是不是无法创建bucket的？？

**Comment by chmod740** [comment]
bucket是不是预先已经创建过了？
如果没有就先在腾讯云的网页控制台先创建一个

**Comment by dempsey123** [comment]
尝试过，事先创建一个但是也不行。而且这个我看网上code：-199的错误，并非是这个invalid_bucket_name

**Comment by dempsey123** [comment]
而且创建目录那段函数，一直无法成功创建目录。就算我事先创建好那个bucket

**Comment by chmod740** [comment]
换个bucket名字再试试
-199 | bucket 的名字不符合规则 | 请检查 bucket 是否只包含了数字、小写字母以及中划线-，是否超过了最大长度限制 850 | 400

**Comment by dempsey123** [comment]
谢了。

**Comment by dempsey123** [comment]
换个个小写的名字（excel-file），然后返回的是code":-133,"message":"ERROR_CMD_BUCKET_NOTEXIST。url返回还是none。是系统时间问题吗？？还是说必须换成24小时制的时间？（已经确认对应的bucket在服务器创建了）

**Comment by chmod740** [comment]
-133 | 指定的 bucket 不存在 | 请检查 bucket 是否拼写正确，或地域信息是否填写正确 | 404

**Comment by dempsey123** [comment]
问题已解决。代码完美。纯属个人问题
